package com.example.ui.theme

import androidx.compose.ui.graphics.Color

// ---- Light scheme ----
val PrimaryLight = Color(0xFF4656D8)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFFDEE1FF)
val OnPrimaryContainerLight = Color(0xFF001159)
val SecondaryLight = Color(0xFF5B5D72)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFE0E1F9)
val OnSecondaryContainerLight = Color(0xFF181A2C)
val TertiaryLight = Color(0xFF00696B)
val OnTertiaryLight = Color(0xFFFFFFFF)
val TertiaryContainerLight = Color(0xFF9CF1F2)
val OnTertiaryContainerLight = Color(0xFF002021)
val ErrorLight = Color(0xFFBA1A1A)
val OnErrorLight = Color(0xFFFFFFFF)
val ErrorContainerLight = Color(0xFFFFDAD6)
val OnErrorContainerLight = Color(0xFF410002)
val BackgroundLight = Color(0xFFFBF8FF)
val OnBackgroundLight = Color(0xFF1A1B23)
val SurfaceLight = Color(0xFFFBF8FF)
val OnSurfaceLight = Color(0xFF1A1B23)
val SurfaceVariantLight = Color(0xFFE3E1EC)
val OnSurfaceVariantLight = Color(0xFF46464F)
val OutlineLight = Color(0xFF767680)
val OutlineVariantLight = Color(0xFFC7C5D0)
val InverseSurfaceLight = Color(0xFF2F3036)
val InverseOnSurfaceLight = Color(0xFFF1F0F7)
val InversePrimaryLight = Color(0xFFBAC3FF)
val SurfaceTintLight = PrimaryLight

// ---- Dark scheme ----
val PrimaryDark = Color(0xFFBAC3FF)
val OnPrimaryDark = Color(0xFF08218A)
val PrimaryContainerDark = Color(0xFF293CA0)
val OnPrimaryContainerDark = Color(0xFFDEE1FF)
val SecondaryDark = Color(0xFFC4C5DD)
val OnSecondaryDark = Color(0xFF2D2F42)
val SecondaryContainerDark = Color(0xFF434559)
val OnSecondaryContainerDark = Color(0xFFE0E1F9)
val TertiaryDark = Color(0xFF80D4D5)
val OnTertiaryDark = Color(0xFF003738)
val TertiaryContainerDark = Color(0xFF004F51)
val OnTertiaryContainerDark = Color(0xFF9CF1F2)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)
val ErrorContainerDark = Color(0xFF93000A)
val OnErrorContainerDark = Color(0xFFFFDAD6)
val BackgroundDark = Color(0xFF121318)
val OnBackgroundDark = Color(0xFFE3E1E9)
val SurfaceDark = Color(0xFF121318)
val OnSurfaceDark = Color(0xFFE3E1E9)
val SurfaceVariantDark = Color(0xFF46464F)
val OnSurfaceVariantDark = Color(0xFFC7C5D0)
val OutlineDark = Color(0xFF91909A)
val OutlineVariantDark = Color(0xFF46464F)
val InverseSurfaceDark = Color(0xFFE3E1E9)
val InverseOnSurfaceDark = Color(0xFF2F3036)
val InversePrimaryDark = Color(0xFF4656D8)
val SurfaceTintDark = PrimaryDark

// ---- Brand accents (icon / gradient) ----
val BrandIndigo = Color(0xFF4353D9)
val BrandViolet = Color(0xFF7B5CE6)
val TerminalGreen = Color(0xFF69F0AE)
